// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWh2xCY5GMxu5S5wRBYenS4AxvBUvfQcI',
    appId: '1:717272588791:web:fb2914849fedd549100ef2',
    messagingSenderId: '717272588791',
    projectId: 'sbs-trading-29380',
    authDomain: 'sbs-trading-29380.firebaseapp.com',
    storageBucket: 'sbs-trading-29380.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDeDTQ8dlKaMk73pR_458KbxUJEpWHK90',
    appId: '1:717272588791:android:a2d81c48e0bf0f1d100ef2',
    messagingSenderId: '717272588791',
    projectId: 'sbs-trading-29380',
    storageBucket: 'sbs-trading-29380.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKICkyupKFyxW3AV-XvpNvVvOAog-L9Lw',
    appId: '1:717272588791:ios:3f5603c1bc645334100ef2',
    messagingSenderId: '717272588791',
    projectId: 'sbs-trading-29380',
    storageBucket: 'sbs-trading-29380.appspot.com',
    androidClientId: '717272588791-prufpuarbf77vogdn4vfhusvhojj92jh.apps.googleusercontent.com',
    iosClientId: '717272588791-t67qhcai4o0ritrtu6hhag2d62nd31tr.apps.googleusercontent.com',
    iosBundleId: 'com.app.cryptocurrencyApp',
  );
}
